### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by DanniN777** [t3nk3y/palia_steam_helper#1]
Thank you for working on this project! 
I followed the video but have been stuck at the extracting files part :( 
![IMG_8248](https://github.com/t3nk3y/palia_steam_helper/assets/142067682/4b871d0f-92c8-4933-877f-52234e48c9c9)

**Comment by t3nk3y** [comment]
Hello DanniN777 are you still having this problem?  If so, can you let me know what system you are running on?  Steam Deck, or another Linux environment?

**Comment by DanniN777** [comment]
Steam Deck. I haven’t modded it or anything just the stock steam deck. I don’t have a Micro SD card just using system storage not sure if that matters or not.

**Comment by t3nk3y** [comment]
No MicroSD required.  However, you do need to have enough space on your primary drive. You need to have at least 30GB of space available.

The step it died on for you, indicates it downloaded the main zip file, which is around 15GB, but then it has to extract that 15GB, and if it got stuck while extracting, then your system may have run out of space.

**Comment by DanniN777** [comment]
Just checked and I have about 100gb of space left. Is there anything else that might be stopping it ?

**Comment by t3nk3y** [comment]
Would you be willing to head over to the Palia discord server in the
#tech-support -> Unofficial Linux/Steam Deck/Max troubleshooting thread?
https://discord.com/channels/809856101326913567/1136399336385806427

We can likely better help you there, and if I'm not around, there are other
people around to help as well.  If we find a bug in the process, or a
feature to make things work better, we will add it.

And if you haven't yet, you should try deleting the folder you put the
script in, make a new one, and try the install command again, to see if the
issue may have already been fixed.  If you already did that, don't waste
your time, just let me know.

**Comment by DanniN777** [comment]
Okay thank you I’ll try the discord!

**Comment by t3nk3y** [comment]
Just wanted to check back in to see if you managed to get things rolling or not.

**Comment by t3nk3y** [comment]
Closing due to activity.  Assume resolved.
